### ISSUE TITLE
More @FoxInFlame Remarks :) (Android Edition #1)

### ISSUE THREAD

**Issue by FoxInFlame** [Drutol/MALClient#109]
As you can see, I have planned multiple editions. 
This one is Android Edition, which means it addresses the Android app version of MALClient, and it is the first one in that edition. 

I have a couple of things I considered as bugs/issues in the Android app version of MALClient, of which half of them I assume you already know.

Imgur Album, again. Titled "More things I noticed about MALClient". Just click/tap the link, and down you will fall into the void of despair, knowing that you still have a long way to go until completion. :)
https://imgur.com/a/cVzxz

**Comment by Drutol** [comment]
Thanks, just please bear in mind that this is 2 months old build :D

**Comment by Drutol** [comment]
@FoxInFlame 

It's hard for me to say anything about most of your remarks because either I'm aware of them or they are already fixed. If you really want feel free to fork the repo and put proper dp/sp values, I'm leaving such things for later when things work.

I'm also planning to add color picker in settings so user can choose whatever accent he wants not only orange, coming from Windows this is must have for me :D
