### ISSUE TITLE
4 suggestions

### ISSUE THREAD

**Issue by RedWavez** [Drutol/MALClient#158]
Hi :D 

I have 4 suggestions for the improvement of the app:

**1º**- **Friend's anime/manga list arrow** - When I click on my friend's anime list I keep forgetting where to click to see his Completed/on hold/Dropped/Plant to watch and All list. I think it's not intuitive and I'm suggesting some sort of an arrow like this: https://puu.sh/xBgkN/ec5fd3f18f.png. I think it would be a lot better and more user-friendly.

**2º**- **More language support** - It would be great to choose the language of the app in the Settings like: Portuguese/German/Russian, etc. Also, for first time users it could appear right when the app started.

**3º** - **More widget costumization** - I have placed the widget on my home screen and I love it, I would love it even more if you could add more features and colours :)

**4º** - **Make filter by genres and episodes** - Another awesome feature is adding the ability to filter anime/mangas by episodes and chapters respectively and also by genres.

These are my opinions,
Thankyou for the great app :+1: 

PS: Sorry if any of these were already suggested/denied.

**Comment by Drutol** [comment]
Hello again!

1. I'm planning to make drawer from right side accessible by swiping, I'm not sure whether I want dropdown arrow there.

2. Languages hmm? There are tons of people raving about this ^^ The problem is that I didn't really plan localization when making it and while changing it isn't very hard it's very daunting task. Personally I prefer having all my apps in English rather in my native language so there's also that.

3. Unless I missed something (which is something very probable) widget customization isn't nice and easy as every variation requires separate layout even if it differs in one aspect. Tell me how would you like it to look and I'll do my best.

4. The problem with such filters is that I often don't have required data when building anime list (like in genres case). As for filtering by episodes... do you mean shows with 12/13 episodes and 20+ ones?

**Comment by RedWavez** [comment]
Hi! Sorry for late response.

1. That's alright it's just that I often missclick it and I thought it would be a minor improvement. If you have a better solution go for it :)

2. Well you can always ask people to support you on the translations.

3. For the widget I would like it to have  "shows airing this week"

**Comment by Drutol** [comment]
2. Yeah I could but I'd have to extract resources for translation first which means tons of copy&paste and days worth of work. It's in plans but with as low priority as it gets.

3. Widgets:
   * Well these are kind of different widgets. 
   * Widget with transparent background is doable but I'm not sure whether it'll look any good. Can try though.
   * Color picker is no go (very probably), 
   * Umm I don't even have such data :D

4. Now you can type in search bar filter phrase "ep >/</= X" or "score >/</= X" to filter by these values. Any other filters that could be useful?

**Comment by RedWavez** [comment]
2 - No problem

3 - It kinda sucks that widgets have to be diferent and you can't choose from a dropdown menu :/ 
 Well these were just ideas, feel free to choose whatever you feel like it will be good (or not) for the app.

4 - Thanks, I needed this! Hummm I'm not sure but maybe a filter by TV, Movies, Ovas, Specials?

**Comment by Drutol** [comment]
4. You can already to this, typing "movie" "tv" etc. will show shows of given type. this works for your tags too :)

**Comment by RedWavez** [comment]
Awesome! I didn't knew about this. I have a question, is it possible to integrate these filters to every anime and not only the ones from my anime list?
Can you allow multi-filter support? For example ep = 12 ^ score >=7

**Comment by Drutol** [comment]
That would require better search API from MAL, I'm waiting for new API which is supposedly in development right now.
I'll think about logic operators between these filters.

**Comment by RedWavez** [comment]
Ok thanks!
