### ISSUE TITLE
Port suggestion

### ISSUE THREAD

**Issue by nandito104** [Drutol/MALClient#194]
Given that the app is made using Xamarin, would it be possible to port it to iOS?

Great work, by the way. Hands down the best MAL client on Android and W10.

**Comment by Drutol** [comment]
Yes it is possible. But... the code in this project right now is big pile of steaming spaghetti because of it being my first bigger project and I was just learning stuff in the beginning. I'd have to rewrite major part of it to even start thinking about iOS. Then, iOS development comes in, I don't have Mac nor iPhone... maybe hackintosh VM laying around so I lack the means to make this app and to top it off Apple Developer account is very costly thing. Also it's a ton of work even when I have shared logic.

Sorry but iOS won't happen. :(

**Comment by nandito104** [comment]
I'm sorry to hear that. Anyways, keep it up!
