### ISSUE TITLE
Feature : change anime priority from the app

### ISSUE THREAD

**Issue by AxelRann** [Drutol/MALClient#264]
Hi, 

Hopefully, this feature is not already in and I  just missed it... 

Anyway, right now, if I add a show to my plan to watch list, I cannot change its **priority** from the app. Instead I have to do it directly on MAL.
Is there a way to do it via the app or could you add it?

Regardless, thanks for this already super useful app! 
Cheers.

**Comment by Drutol** [comment]
Hello,

I'm afraid that's not available right now. Probably because it was not possible to change it when API was still a thing. How does priority work? I guess I'd want to use it for sorting?

Edit:
![image](https://user-images.githubusercontent.com/6102530/60755135-77599000-9feb-11e9-89f3-64f8fb458d5a.png)

Oh so it's just one of 3 values. I guess it would look cool on anime list with 3 coloured labels with priority.

**Comment by AxelRann** [comment]
Yeah, I use it for sorting. I check my plan to watch list only occasionally, but when I do the priority tag is pretty useful (since there are obviously some shows I look forward to a bit more than others :p).

Do you think it is possible to add in the app (technically speaking I mean. I'm not asking for a time frame ;) )?

**Comment by Drutol** [comment]
![Screenshot_2019-07-14-18-33-38-923_com drutol malclient](https://user-images.githubusercontent.com/6102530/61186464-fc851a80-a665-11e9-8f75-4310d761bb1c.png)
How does that look? 

The default "Low" is green and hidden by default (there's a setting to always show them).
Change option is in the "..." menu.

**Comment by Drutol** [comment]
Ah well /shrug

Added. :)
