### ISSUE TITLE
[Live] BETA Forums mega(I hope so)thread.

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#44]
This thread will serve for all forum related stuff once it's released next week.

### What's in it? 
* Latest fixes from #42.
* First iteration of forums implementation.

### Important points:
* Which links I forgot to trigger in-app.
* What settings would you like to have there?
* Navigation.
* Topic page skin issues.
* What happens after creating new topic?

### Download links for non-store versions:
* x64 v4.4.19
https://1drv.ms/u/s!Am1xQK-HVf_Ikep68kd7BPybntXERA
* ARM (I've tested this much less thus far) v4.4.20
https://1drv.ms/u/s!Am1xQK-HVf_Ikep7wrZBLWpPAPyPNA

**Comment by Kimod** [comment]
Maybe some of these are intencional, just sharing what I so far found, will edit later with more stuff
* When someone quoted someone, then clicking on http://puu.sh/qsP5U.png "Benkyo said:" opens website
* When you click on "Report" on a comment, it opens the website
* When you click on "BBCode". It's below making comment box, next to Submit and Cancel, it opens website
* Clicking on almost everything here - http://puu.sh/qsPbm.png (Top, Anime, Top, Forum and Title Discussion) opens website
* Some people have their list as a signature link, so it open's their list opens in a browser
* In this situacion I would expect that back button would return me to the discusion, not to the main forum page - http://puu.sh/qsPiP.gif
* When I click on "Forum board" in that right viewer more than 1 time and then try to go to for example "Updates & Announcements" it still opens that "Forum board" - http://puu.sh/qsPyH.gif
* You are probably aware of this, but you can't search topics, right?
* When you hover over their signature image, you could have link appear as a mouseover text (if they have one)

**Comment by Mordonus** [comment]
Yeah I'm aware of some of this stuff but I wanted get an input from different perspective ^^

**Comment by Mordonus** [comment]
The plan (pretty realistic tbh) is to release this to the store somewhen before next weekend. "Less buggy" beta ^^.

**Comment by Mordonus** [comment]
Uploaded new builds

**Comment by Kimod** [comment]
My observations and opinions of the new build
* I think that the search thingy should be in top right corner, so it is consistent with the rest of search icons - http://puu.sh/quluY.png (maybe have it a little different, extended by default and clicking on magnifier will send what is written there)
* This is what I meant with that mouse over - http://puu.sh/qulCZ.jpg yea, it won't be possible, shame that there are these sort of limitations…
* When I click on a link that links to different forum page, it functions correctly in the app, but also opens the page in browser
* Maybe when the search didn't find anything, show something like "No data received from MAL, try searching for something more specific. :(" instead of not doing anything
* And maybe you could somewhere add an option to "Edit your signature" and link them to this link - http://myanimelist.net/editprofile.php?go=signature or maybe somehow integrate it to the app, but I think that is unnecessary
* Ok, I will just describe on what to click on and you will probably know what's wrong - "Updates & Announcements" -> "MAL's New Social Media Pages", find user "PriestSlayer" (it's 29th comment) and click on "FragOutFire said:" in his signature, for me, it opens the page in browser but also the app will never load that link

But wow, used it for almost 2 hours and didn't find anything major, well except sometimes long loading times, but that is something you just can't influence… MAL forums are certainly an interesting place… :D Enjoyed my time there, can see myself going there, especially when I will always see that "Forums" in hamburger menu ^^ 
And also I think that I don't say it enough, especially when I'm always telling you, what is wrong, but I really appreciate all the work you put into the app ^^

**Comment by Kimod** [comment]
* When I click on pinned topic and then go back, "0" is the title for the category I was earlier - http://puu.sh/qwud1.gif 
* When I click on pinned topic on homepage of Forums and then go back with that back button, it goes through an empty list - http://puu.sh/qwuqn.gif
* On mobile, sometimes instead of the post loading, it crashes
* Now when the "News" are in "Forums", shouldn't you remove them from hamburger?
* And a little question: Do you plan to implement the mobile style website forum to mobile app in the future?

**Comment by Kimod** [comment]
* "<- Previous week" in "News Discussion" in Forums opens it in website http://puu.sh/qxGTx.png You can somehow redirect it to News right? (this "<- Previous week" opening in browser is also in "News" but you want to point out forums only bugs ^^)
* In forums Anime opens in it's right viewer - http://puu.sh/qxH5W.gif but manga doesn't - http://puu.sh/qxH7t.gif
* In News clicking on "x Comments" http://puu.sh/qxGVP.png opens in website, now you can redirect it to open in forums
* After every "&" in Categories is "amp;" http://puu.sh/qxHPH.png - http://puu.sh/qxIjC.png

**Comment by Mordonus** [comment]
I was about to press "build for the store button" nice timing :D

**Comment by Mordonus** [comment]
Forums now in certification!

```
13.08.2016 -  v4.4.22.0 & v4.4.21.0

Added forums!
Fixed mobile sort by start/end date.
Resolved multiple navigation issues in mobile version.
Visually tweaked search page.
Clicking on any anime item should always trigger details navigation.
Desktop upper navigation bar will behave better now.
Small tweaks and fixes everywhere :)
```

**Comment by Mordonus** [comment]
Forums on mobile will now use mobile MAL layout :)
