### ISSUE TITLE
App stats for July

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#45]
Yet another month passes... stats time!

There is slight increase in users:

![image](https://cloud.githubusercontent.com/assets/6102530/17464442/e85045c2-5cde-11e6-80fe-c170b44d52ed.png)
 Sessions:

![image](https://cloud.githubusercontent.com/assets/6102530/17464445/02588ba0-5cdf-11e6-9cd6-d26b902a7386.png)

Donations have "sky-rocketed" past week:

![image](https://cloud.githubusercontent.com/assets/6102530/17464448/25746c80-5cdf-11e6-8b37-e3f302930a70.png)

**Comment by Amrykid** [comment]
Good to see that things are going strong here. Keep up the good work @Mordonus !

**Comment by Mordonus** [comment]
I'll probably make reddit thread this month so numbers should rise even more :)

**Comment by Mordonus** [comment]
Btw, any ideas where to promote this app?

**Comment by Amrykid** [comment]
Besides /r/windowsphone .... maybe /r/windowsapps ? If you get the UI working nicely for Xbox one, you could post it in /r/xboxone as well.

**Comment by ZeroOmar** [comment]
I could tell you Facebook and twitter but that might look like the fake ads about "know who visited you profile" if you commented too much.
and like you posted before reddit is a good place to start. posting about it in anime related subreddits and making your own thread.

I know another developer who uses reddit for feedback instead of github.
here is his subreddit www.reddit.com/r/KissAnimeEssentials/ 
maybe you could help each other ;-)

**Comment by Mordonus** [comment]
So far I have posted on
 * /r/windowsphone
 * /r/windowsapps

once in April when dekstop version launched.

Now I'm posting regularly on
 * AppRaisin
 * MAL Forums

I feel like forums are big enough to bring this up on reddit once again ( + there were a few requests in previous post). 

Additional means of increasing user-base:

Localization is something that comes to my mind from time to time but having most of the content in English I'm not sure whether it's the best idea...

Maybe somewhen towards end of a year I'll work on android version with Xamarin as there were a few reviews stating that I can compete there feature-wise. (I'll probably team-up with somebody here as this is quite big endeavour)

As for xbox... last console I had was PS1 I have no clue how this interface works nor had I held pad in my hands in years... (how about holographic MAL + 3D waifu :D?) deploying to xbox wouldn't probably be very problematic because UWP but it's *very* unfamiliar environment to me.

If I were to create subreddit now the amount of users would be surely too small maybe when there's more people it would be useful but not now.

**Comment by Amrykid** [comment]
3D WAIFU!?!?!?! Sign me up!
