### ISSUE TITLE
Gridview width - Desktop

### ISSUE THREAD

**Issue by cortk** [Drutol/MALClient#47]
On W10 desktop, width of the gridview for anime is decreased if default hamburger state is collapsed. 
![snip1](https://cloud.githubusercontent.com/assets/5999060/17739701/4e44ea5c-64d9-11e6-9363-11b01123685a.JPG)

**Comment by Mordonus** [comment]
Hi there! That's because there's not enough width to fit another column of items, I cannot really do much about it :(

**Comment by cortk** [comment]
1 image shows it after clicking on an anime listing, and the other one after I close it again. Somehow there's enough room to fill it? Screen size 1680x1050
![snip3](https://cloud.githubusercontent.com/assets/5999060/17752442/2b98a9b8-650f-11e6-80ec-18399ba1bf4b.JPG)
![snip2](https://cloud.githubusercontent.com/assets/5999060/17752443/2bc31540-650f-11e6-81ee-566daca1da4a.JPG)

**Comment by Mordonus** [comment]
I have adjusted some things but to be honest I wasn't able to reproduce this issue... We'll see with next build :)

**Comment by Kimod** [comment]
This bug is due to certain bug with scrollbar... When you start up the app, the scrollbar isn't at the edge of the window (and in grid view, it is little more to the left than it is supposed to be). The thing that moves scrollbar to the edge is when you open anime details. When you close them, you move the scrollbar to the right which creates more space for grid items, so now it can fit one more column. Drutol already knows about this issue so let's hope it gets resolved soon™ ^^

Me recreating this bug
![grid view scrollbar](https://cloud.githubusercontent.com/assets/6088494/17824501/b4613d4c-6662-11e6-9d02-84b40e170bc2.gif)

**Comment by Drutol** [comment]
Okay okay I get it... it's fixed this it is the end of this bug's long lived career. Or is it? Find out in next update!
