### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#50]
So there's a thing, I got a few emails where people were offering help translating this app. I made research and started implementing foundations but god, t's so mundane that my eyes started melting and I only extracted like 100 strings.

Yay or Nay for localization, is there even reason while most of the content is in English? Because the longer I'm thinking about it the less I want  to have anything to do with it...

**Comment by Kimod** [comment]
Nay

When I use apps for browsing sites that are in english, like reddit or mal, I think that it's unnecessary to have that app translated to different language... We use those apps/sites, because we already know english.
Apps like counters or alarms have purpose in translating, because you can translate the whole thing and there won't be any other language.
I don't say it would be pointless, but it would be pain. Finding every string that should be translated, making a system where others would submit their translations and then actualy translating. If you would roll out an update that would implement some things that would need to be translated and the other person who translated something wouldn't be around/stoped carrying, you would end up with mixed english and that language translation. 

But if you will end up making localization, count me in translating your app to Czech ^^

**Comment by Drutol** [comment]
Xamarin then!
