### ISSUE TITLE
Emm... am I doing this correctly?

### ISSUE THREAD

**Issue by Drutol** [Drutol/MALClient#62]
I've beenworking on countdown till next episode but the more I'm thinking about this the more confused I am...

![image](https://cloud.githubusercontent.com/assets/6102530/18806801/7ffc604a-8237-11e6-8e42-d85d59d2a9f8.png)
(This is with timezone offset... it must be alright, right?)

I hate timezones btw xd

**Comment by Drutol** [comment]
+ @Kimod : I've (probably) fixed this issue which I was avoiding with days on shows that are no longer airing. ^^

**Comment by Kimod** [comment]
* This countdown looks good, I'm sure that timezones are hell :/ Huray on solving that issue with days still remaining visible! 
* And sorry if unrelated, but could you somehow show on airing shows that new episode is available? I don't really know how you could make it work, but I believe in you ^^ (bot Roboragi somehow made it work https://www.reddit.com/r/Animesuggest/comments/547t2d/visually_stunning_anime/d7zv1gl and is also on github (click on source on that comment) , so maybe you could inspire yourself? :3) 
* And also I saw that you said that rewatching isn't possible, but the app I use on android somehow made it work, the only thing that is API limitation is pulling the Rewatched times thing - http://imgur.com/a/XLFu4 (sorry if those images were useles and AFAIK the app isn't open source)

**Comment by Drutol** [comment]
* They sure are...
* Maybe some day... this is so freaking tricky due to obtaining data from html... aaagh my head hurts!
* To be honest I have no clue how rewatching works on mal and I have never used it. All I know is that somebody said it's bugged on MAL API club and I decided to do notifications instead.

**Comment by Kimod** [comment]
If someone is rewatching something, it will set 'my_rewatching' to 1 - http://puu.sh/rmlOd.png and the amount of rewatched episodes is 'my_watched_episodes' (so I guess nothing new) and notice the 'my_status' is set to 2, which means completed (at least I think), so you will have to somehow get it to watching tab in your app. To rewatch something you have to click on 'Re-waching' checkbox - http://puu.sh/rmm4L.png in 'edit' and as I said, the only thing that is bugged is that you can't obtain the 'Total Times Re-watched Series' from the API, but you can send it... (at least from android app I use). I hope I helped somehow ^^

**Comment by Drutol** [comment]
God dammit... okay okay I'll look into this thing

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/18810844/623214ba-82a0-11e6-9c23-43b29caf041a.png)

No comment

**Comment by Drutol** [comment]
Ok, now I have to make UI for this and we are all set ^^

**Comment by Drutol** [comment]
🎉 
![image](https://cloud.githubusercontent.com/assets/6102530/18813676/642193e2-8302-11e6-85d9-c8502b38039b.png)

Now I'm preparing to push this build to the store... I still have to fix desktop forums ;d

**Comment by Kimod** [comment]
I think you should have 0 times rewatched in that list too, so you can reset it from the app... Other than that, it looks pretty cool ^^ And how does it work with My Start and My End? Does it overwrite the date before, or will it set it only if you haven't got any date before? Or is it purely coincidence? (I'm asking since you have My Start set to today)

**Comment by Drutol** [comment]
I did set watching in the meantime and I did not have start date previously so it set it for me, 

It does not change start/end dates nor current status. All what is changed is number of watched eps and rewatching flag.

I'll send you test version in a few hours ^^

**Comment by Drutol** [comment]
calendar countdown, rewtaching, notifications, better forums, major hummingbird fixes

x64:
https://1drv.ms/u/s!Am1xQK-HVf_IkslM3MwSUKplcMnjTg
ARM:
https://1drv.ms/u/s!Am1xQK-HVf_IkslLTVOOBHJy_Oh2Hw

**Comment by Kimod** [comment]
Rewatching doesn't work properly, I was really confused why it didn't work, because it seemed like it worked first time (it didn't work, it just seemed like it worked) There are a couple of problems
* It doesn't send MAL that I'm rewatching something, so when I refresh the list, it's like I'm not rewatching it - http://puu.sh/rncRP.gif
* It doesn't recognise if I'm something rewatching - http://puu.sh/rncJo.jpg

So that means it doesn't send and read the rewatching flag properly?
Maybe those two are related, just my observation ^^

**Comment by Drutol** [comment]
Hmm I think I know where's the mistake... How about the rest?

**Comment by Kimod** [comment]
Everything else works, how exactly are the notifications working? I have one unread notification that I kept unread, will the app eventually pull it? I didn't have the version with just notifications, so it may just take a little time, especially with the crappy windows 10 notifications (I even have problems with Outlook app......)
If you want some bugs here are a few
* Profile "RayAdha"'s favorite anime isn't high, because the first anime "Doraemon (1979)" doesn't high enough anime cover picture - http://puu.sh/rnekI.jpg
* And if favorite people doesn't have picture, they aren't fully scretched - http://puu.sh/rnemd.jpg
* This is still a thing - When I click on pinned topic and then go back with that back button, it goes through an empty list - http://puu.sh/qwuqn.gif
* I was wondering if you did something about this, you didn't xD - http://puu.sh/rnetA.jpg (time and show's season both enabled)

**Comment by Drutol** [comment]
Yeah, notifications or rather BG tasks that fetch them are one big unknown. It did fork for me a few times though... You can always trigger them in settings tab :)

**Comment by Drutol** [comment]
Can you send me this script from #58 ?

**Comment by Kimod** [comment]
this? (edit comment to see it :3)
<script>
window.MAL.notification = {"items":[{"id":"12947861","typeIdentifier":"related_anime_add","categoryName":"New Related Anime","createdAt":1474566833,"createdAtForDisplay":"Sep 22, 7:53 PM","isRead":false,"url":"https:\/\/myanimelist.net\/anime\/34103\/Danganronpa_3__The_End_of_Kibougamine_Gakuen_-_Kibou-hen","isDeleted":false,"anime":{"title":"Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen","mediaType":"Special"}}],"historyItems":[]};
window.MAL.notification.hideEmpty = false;
window.MAL.notification.templates = {"main":"<section class=\"notification-section\"><notification-list\n            :items=\"items\"\n            :check-items=\"checkItems\"\n            :items-checked-in-this-session=\"itemsCheckedInThisSession\"\n            :is-history=\"false\"><\/notification-list>\n\n                                          <div class=\"notification-pagination\">\n                      <\/div>\n\n        <\/section>","list":"      <div>\n        <div v-if=\"!isHistory\" class=\"notification-header normal\">\n          <div class=\"right-menu\">\n            <span class=\"item mark-all\"\n              :class=\"{disabled: !hasUnreadItems}\"\n              @click=\"checkAllItems\">\n              <i class=\"fa fa-check mr4\"><\/i>Mark All as Read\n            <\/span>\n          <\/div>\n          <h3>New Notifications<\/h3>\n        <\/div>\n        <div v-if=\"isHistory\" class=\"notification-header simple\">\n          <div class=\"right-menu\">\n                      <\/div>\n          <h3>History<\/h3>\n        <\/div>\n\n        <ol class=\"notification-item-list\">\n          <li class=\"notification-item\"\n            :class=\"[item.typeIdentifier]\"\n            v-for=\"item in items\">\n            <a v-if=\"item.url\" @click=\"checkItem(item)\" :href=\"item.url\" class=\"background\" target=\"_blank\"><\/a>\n            <div class=\"notification-item-layout\">\n                            <component v-if=\"!item.isDeleted\" :is=\"resolveComponent(item)\" :item=\"item\"><\/component>\n              <div class=\"notification-item-content\" v-if=\"item.isDeleted\">(deleted)<\/div>\n                            <span class=\"time\">${item.createdAtForDisplay}<\/span>\n                            <span class=\"is-read\"\n                v-show=\"!item.isRead || isItemCheckedInThisSession(item)\"\n                :class=\"{checked: item.isRead}\"\n                @click=\"checkItem(item)\">\n                <i class=\"fa fa-check\"><\/i>\n                <i class=\"fa fa-check-circle\"><\/i>\n              <\/span>\n            <\/div>\n          <\/li>\n          <li class=\"notification-item empty\" v-show=\"items.length === 0\">\n            <div class=\"notification-item-layout\">\n              <p>No ${isHistory ? \"history\" : \"notifications\"}.<\/p>\n            <\/div>\n          <\/li>\n        <\/ol>\n      <\/div>\n    ","itemFriendRequest":"      <div>\n        <div class=\"notification-item-content with-actions di-tc\">\n          <a :href=\"item.friendProfileUrl\">${item.friendName}<\/a>\n          sent you a friend request${item.message.length ? \":\" : \".\"}\n          <q class=\"message\" v-if=\"item.message.length\">${item.message}<\/q>\n        <\/div>\n        <p class=\"actions di-tc\">\n          <span v-if=\"!item.isApproved\">\n            <span class=\"action-button accept\" @click=\"accept\">Accept<\/span><span class=\"action-button deny\" @click=\"deny\">Deny<\/span>          <\/span>\n          <span v-if=\"item.isApproved\">\n            <span class=\"result\">Accepted<\/span>\n          <\/span>\n        <\/p>\n      <\/div>\n    ","itemFriendRequestAccept":"      <div class=\"notification-item-content\">\n        <a :href=\"item.friendProfileUrl\">${item.friendName}<\/a>\n        accepted your friend request.\n      <\/div>\n    ","itemFriendRequestDeny":"      <div class=\"notification-item-content\">\n        <a :href=\"item.friendProfileUrl\">${item.friendName}<\/a>\n        denied your friend request.\n      <\/div>\n    ","itemProfileComment":"      <div class=\"notification-item-content\">\n        <a :href=\"item.commentUserProfileUrl\">${item.commentUserName}<\/a>\n        posted a comment on your profile${item.text.length ? \":\" : \".\"}\n        <q class=\"message\" v-if=\"item.text.length\">${item.text}<\/q>\n      <\/div>\n    ","itemForumQuote":"      <div class=\"notification-item-content\">\n        <a :href=\"item.quoteUserProfileUrl\">${item.quoteUserName}<\/a>\n        quoted your post in the\n        <a class=\"page-title\" :href=\"item.topicUrl\" :title=\"item.topicTitle\">${item.topicTitle}<\/a>\n        topic.\n      <\/div>\n    ","itemBlogComment":"      <div class=\"notification-item-content\">\n        <a :href=\"item.commentUserProfileUrl\">${item.commentUserName}<\/a>\n        posted a comment on your blog.\n      <\/div>\n    ","itemWatchedTopicMessage":"      <div class=\"notification-item-content\">\n        A forum reply was posted on your watched topic\n        <a :href=\"item.topicUrl\" :title=\"item.topicTitle\">${item.topicTitle}<\/a>.\n      <\/div>\n    ","itemClubMassMessageInForum":"      <div class=\"notification-item-content\">\n        <a :href=\"item.sharedUserProfileUrl\">${item.sharedUserName}<\/a> shared the discussion\n        <a :href=\"item.topicUrl\" :title=\"item.topicTitle\">${item.topicTitle}<\/a>\n        in <a :href=\"item.clubUrl\" :title=\"item.clubName\">${item.clubName}<\/a>.\n      <\/div>\n    ","itemUserMentionInForumMessage":"      <div class=\"notification-item-content\">\n        <a :href=\"item.senderProfileUrl\">${item.senderName}<\/a>\n        has mentioned your name in the\n        <a class=\"page-title\" :href=\"item.pageUrl\" :title=\"item.pageTitle\">${item.pageTitle}<\/a>\n        <span v-text=\"{\n          user_mention_in_forum_message: 'topic',\n          user_mention_in_club_comment: 'club'\n        }[item.typeIdentifier]\"><\/span>.\n      <\/div>\n    ","itemOnAir":"      <div class=\"notification-item-content\">\n        The anime you plan to watch began airing on ${item.date}:\n        <template v-for=\"anime in item.animes\">\n          <a :href=\"anime.url\">${anime.title}<\/a><template v-if=\"$index < item.animes.length - 1\">, <\/template>\n        <\/template>\n      <\/div>\n    ","itemRelatedAnimeAdd":"      <div class=\"notification-item-content\">\n        <a :href=\"item.url\">${item.anime.title}<\/a>&nbsp;(${item.anime.mediaType}) has just been added to the database.\n      <\/div>\n    ","itemPaymentStripe":"      <div class=\"notification-item-content\">\n        <i>${item.planName}<\/i> has been suspended, because the payment for your subscription was unable to be processed.\n      <\/div>\n    "};
</script>

**Comment by Drutol** [comment]
Sneaky sneaky

**Comment by Drutol** [comment]
I guess I'll have to send you debug build because this input data works for me...

**Comment by Drutol** [comment]
💥 **CRASH THIS AS MUCH AS YOU CAN** 💥 

https://1drv.ms/u/s!Am1xQK-HVf_Ikspog4uM-7pSc0qgXA

**Comment by Drutol** [comment]
Caught one!

**Comment by Kimod** [comment]
༼ つ ◕..◕ ༽つ Crashes happened ༼ つ ◕..◕ ༽つ

**Comment by Drutol** [comment]
It seems that messages are crashing, do you have any? Try disabling them in settings and try again xd

**Comment by Kimod** [comment]
Yup, it works without messages checked - http://puu.sh/rnw76.gif , I don't think I have any messages - http://puu.sh/rnwfm.png

**Comment by Drutol** [comment]
Yeah, I was throwing my own exception which I forgot to catch, and it went free..... 🎈

**Comment by Kimod** [comment]
So will you try to solve this crash that just happened? I quickly clicked on friend's friends - http://puu.sh/rnx5O.gif crashed it 2 times

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/18817411/ccfc9d50-835f-11e6-8446-8b43233d1523.png)

Bam, and I know what's happening now. Crash this thing more ^^

**Comment by Kimod** [comment]
* If you click on History, Load characters in anime details, or Calendar (that wasn't previously builded) without internet connection, it will crash. 
* This isn't a crash - how is this possible without internet connection? I loaded them before with internet, the scores are actually stored but they for some reason won't be displayed - http://puu.sh/rnzQR.gif
* Ugh how do I make the notification to not notify me again? Do I have to go to the website and mark it as Read?

I didn't found any more ways to crash your app, it went through a lot of nasty things :3

**Comment by Drutol** [comment]
Read notifications are stored in cross-device storage and they only appear once for me. Maybe it's something with debug version itself.

**Comment by Drutol** [comment]
```
27.09.2016 v5.0.19 & v5.0.18.0

Added notifications!
New store logo!
Added calendar episode countdown!
Added re-watching support.
Improved forums.
Major Hummingbird fixes.
Various tweaks and fixes.
```
