### ISSUE TITLE
Walk Through, "Recent Posts" etc.

### ISSUE THREAD

**Issue by sinofanger** [Drutol/MALClient#65]
I was one of the first to download the app and use it a couple of months back. Boy, the app has improved a lot over the past few months. You even included the forums irrespective of the fact that MAL api is kinda messed up. The app is really good now.

Now coming to my suggestions, the app has a lot of features. it would be good to include a walkthrough screen for first time users. Or else it will take some time for non-tech savvy person to find his/her way around when they download the app for the first time

Second thing is, in the forum section it would be good to have "**my recent forum posts**". This is because if the user is very active in the forums, it would help him/her to keep track with their recent posts and forum comments. Or is it already there in the app? I could not find it.

Also, why is the cache time limited to 1 day? Won't allowing increased cache duration help in load times?

**Comment by Drutol** [comment]
Hello there!

For starters, MAL's API is **really** messed up and lacking :) For like 75% of features I had to create my own "api" based on html scrapping.

As for walk through, I don't really have an idea how to it. Creating interactive guide with pointers floating around would be pretty complex and time-consuming. What's left is making user go through "image guide" on first run or creating one-pager website and pointing people there on startup. I'll think a bit more about it :)

Is there "my recent forum posts" page on mal forums? I was trying to find it but to no avail. If there's no such thing it'll be almost impossible for me to add this, or do you mean searching for posts by user?

It's only 1 day in order to avoid synchronization issues. If you change something on mobile, then on desktop then in different app and finally on site you will see some strange things ^^

**Comment by sinofanger** [comment]
Yes, you did a very good work. Even in iOS and android no one bothers to create such a beautiful app for MAL because of their api.

I think, an image walkthrough is good enough. Like the "Microsoft Health" app. When we open the microsoft health app, there is a section called "What's new". When we click on it, it gives some image walk throughs and related information.

Now, about recent forum posts. Yes, in the "profile" section, there is a page called "forum posts". It shows all our latest forum posts and comments. For my profile in MAL, the url is: https://myanimelist.net/forum/index.php?action=search&u=dormantking&q=&uloc=1&loc=-1

**Comment by Drutol** [comment]
The plan is to conquer Android and iOS too :D

Okay, it's time to open GIMP again... ahh...

This history should be easy enough, brb.

**Comment by sinofanger** [comment]
And about the website. Let me know if u want a domain or anything. I will be happy to buy it for the continued development and expansion of the app. 😃

**Comment by Drutol** [comment]
🎉 
![image](https://cloud.githubusercontent.com/assets/6102530/19019763/8ab53ac8-8892-11e6-8614-7617dda77bcb.png)

Thanks for the offer!

**Comment by sinofanger** [comment]
Wow 😆

You immediately implemented it. Just awesome. 

By the way, I wanted to ask, is it possible to progressively load information when it comes to “news” and “articles” sectionl. I have two internet connections. One is a 28mbps and the other is  1mbps. In the 28mbps lan, “articles” section and “news” load pretty fast. But in the other connection, the circular loading image keeps on showing for around 30seconds before the posts get displayed.

It might be due to the fact that MAL is using very high quality images. When we look at many countries, the internet speed is still pretty low. So, if there is some way to progressively load the information, the **app will seem faster than the real website** for people with low internet speeds.

**Comment by Drutol** [comment]
You are welcome, when someone bugs me here to do something I tend to do the things faster.

We are talking about index,right? Or news/article content?

**Comment by sinofanger** [comment]
News/article seem way slower than index. Yes, it would be good if index can also be progressively loaded. That is what an user sees first when they open the app, so if it appears to be faster, end-users will always prefer the app rather than opening the website every time.

**Comment by sinofanger** [comment]
<img width="322" alt="mal" src="https://cloud.githubusercontent.com/assets/9476430/19019877/e6a70138-88b3-11e6-80d6-0329a6230e29.PNG">
Take a look at the screenshot above. Can you  put some icon in the red circular area which can point to the "_My recent forum posts_" section. 

Also, "Support Me" and "Feedback" should come after the "Settings and more". And move the "Profile" section" to the top most. Because a user who is very active in MAL will always be signed in and he/she will get faster access to their profile, if its at the top most of the hamburger menu. Profile icon should be circular. That's more in-tune with windows 10 design.

These are all just my suggestions and thoughts. Hihi hope am not bugging too much 👍

**Comment by Drutol** [comment]
[To the previous comment]
The things with pulling html is that I have to pull everything. 

When it comes to index all what's downloaded is around 135KB worth of text. Images are downloaded by asynchronously by app.

Post content on the other hand is rendered using web view due to content's complexity and I have nearly 0 control on what this control does. I can not even change the colour of scroll bar... but even then images are loaded while text content is already visibile.

I cannot really do things differently here :(

**Comment by Drutol** [comment]
White theme... my eyes...

Here you go:
![image](https://cloud.githubusercontent.com/assets/6102530/19019927/34097a66-8899-11e6-9006-cb42fbd831f6.png)

I'm not going to change the order of these button though. I feel like changing them now would be confusing for current users.

**Comment by sinofanger** [comment]
Wow, looks good. Yea true, current users might be confused. Hmm, I think the black theme looks even better than the white one. This black theme has  a  bold look and feel to it. lol, by the way I was using white theme to be in sync with my windows 10 theme settings :P.


When I was resizing the windows, some elements are going out of proportion. Can you please take a look?

<img width="559" alt="resize 2" src="https://cloud.githubusercontent.com/assets/9476430/19019973/8b0077b0-88b8-11e6-97dd-41972316e630.PNG">
<img width="353" alt="resize 1" src="https://cloud.githubusercontent.com/assets/9476430/19019974/8b76b844-88b8-11e6-96fe-3aeee2fb82f6.PNG">

**Comment by Drutol** [comment]
Are you sure?

![gif](https://cloud.githubusercontent.com/assets/6102530/19020015/e31f69f4-889c-11e6-87e7-b1041f2f33e0.gif)

Seems fine to me.

**Comment by sinofanger** [comment]
Can you try doing the same in the white theme? I just tried again, it is the same.

**Comment by Drutol** [comment]
I don't believe that theme has anything to do with this...

![gif](https://cloud.githubusercontent.com/assets/6102530/19020054/10a7bb78-889e-11e6-9bc7-ce8d6c45cc7d.gif)

Gimme a gif ^^

**Comment by sinofanger** [comment]
Hmm, weird. It is not that fluid in my system. Let's see, I will look at it again after a system restart sometime.

By the way, I have a random suggestion, not related to bugs or any. May I say?

**Comment by sinofanger** [comment]
Not related to the previous comment. Can you include a "trailer" section in the anime details page (marked with red)?
<img width="960" alt="trailer" src="https://cloud.githubusercontent.com/assets/9476430/19020155/ad421f5e-88bd-11e6-89f6-72adb75317d1.PNG">

Most anime in MAL has a trailer or preview attached with it. Watching trailer or preview is very important when it comes to browsing an anime. So I think, a trailer section would be really good.

**Comment by sinofanger** [comment]
Also, even though I am logged in via MAL , it is still showing the login page under "Accounts" in the "Settings". It says, "Logged in as DormantKing" but still the login form is being displayed. It would be good, if the profile information can be displayed instead of that login form, if users are already logged in.
<img width="952" alt="login" src="https://cloud.githubusercontent.com/assets/9476430/19020180/65cf9236-88be-11e6-96e6-5e6242ceed89.PNG">

**Comment by Drutol** [comment]
As for previews I personally never look through them when looking out for new shows but I can see the appeal, I'm not going to add this in next update because I'm running out of time a bit but it should make it in next one.

This login form is there in case you want to re-log, log out, log in to hummingbird. I'm swapping this button out from hamburger to settings when user authenticates.

**Comment by sinofanger** [comment]
Hey @Drutol  did you begin android development? If so, try to test on maximum devices before releasing in play store even as a beta. In play store users simply give poor ratings to an app when the app crashes. And since there are 1000s of varieties of android devices (plus tons of custom roms and android versions), debugging will be a pain.  So be a little careful when you make the app public. Because once you get poor ratings for initial releases it will be very hard to make the app popular in future

If you have not begun android development yet, try to look into iOS first. Its easier for debugging and you won't have to worry about device variations and platform dependency much. And iOS also can will give you access to a large user base.

It is not because I am an apple fan boy. I am talking from a developer's perspective. That is why most big companies release iOS app first and then come to android.

**Comment by Drutol** [comment]
The thing is that @lzimon took iOS and I'm in charge Windows,Android and shared logic ^^. Currently there's like nothing as I'm exploring the environment. I want to have something before Winter 2017 season but it may be still too soon :)

If there's one thing I've learnt from my previous "production" transitions it is to wait about a month since "deciding" to go live and during this period fix things because there's indefinite amount of them ^^. Heck, I'm still fixing things here since February release.

@Kimod, you seem to have competition xd

**Comment by Kimod** [comment]
What can I do... I'm always jelous, when senpai doesn't notice my issues and is solving others... :/

**Comment by Drutol** [comment]
Hey, I thought we had this scrollbar issues behind us...

**Comment by Drutol** [comment]
It would be easier for me to develop this thing if there was W10M only. I'm pretty sure that MSFT has the best development environment at least from my experiences (and f-words during my internship project) :)

I for one am going to sink with this ship if it ever sinks (hope not).

"Higher revenues", eh? My primary goal here is to learn new stuff and see people using my app. It's just voluntary work (I got whole $30 since March ^^). But I have to agree with you, iOS has everything pricier and people are more willing to buy stuff.

Wait for something like Decemeber and maybe just maybe there'll be apk waiting for you. In theory I have to **just** create  UI on android and hook everything up to existing things.

**Comment by sinofanger** [comment]
Cool, I will be waiting. Well u don't have to worry. Even if windows 10 mobile sinks, the pc and tablet version of windows 10 will keep on growing. They are already at 400 million devices. 

So I think MSFT app development future is bright and sunny.
