### ISSUE TITLE
Add Anilist support

### ISSUE THREAD

**Issue by Janvicttor** [Drutol/MALClient#87]
Hello,
I'm an Anilist user and feel the lack of an app with support for the site.
I would like to ask, please add AniList support in MALClient for Windows 10.

**Comment by Drutol** [comment]
Well, the reason why I was able to add hummingbird (which is now dead) support was primarily because they provided MAL identifier. If there's a way to convert these ids I can say that adding support for anilist would be *very easy*. If there's not, it will be **much** more complicated.

Thanks for suggestion but while I'll keep this in mind it's just me handling 3 platforms including android and I don't have too much time on my hands... sorry :(

*I got a nice idea though ^^*

**Comment by Janvicttor** [comment]
I'm not a programmer, nor do I understand about. But according to a programmer who I contacted earlier with the intention of asking for the implementation of the AniList in your app, the AniList API is much simpler than MAL, making the job easier. And in addition, users contribute contently helping with development issues.

I appreciate your reply and I understand your priorities for the app. Wish success in developing, since your app is the best on the Microsoft platform.

**Comment by Drutol** [comment]
It's not really the matter of AniList api being complicated or not. To be honest MAL's api is an utter garbage and *every* api is better. The problem is the missing infrastructure for other identifiers. If AniList can provide all data (in convertible format) that I'm currently forcibly taking from mal then there's little problem but as soon as dicrepencies appear this is going to be problematic. I didn't have time to research it yet and I'm focued on android right now.
