### ISSUE TITLE
Auto refresh after completing a series (and other things)

### ISSUE THREAD

**Issue by Accelyte** [Drutol/MALClient#90]
Just a quality of life suggestion, so when you finish a series in the 'Watching' tab it automatically disappears (because it's completed ._.)

**Comment by sinofanger** [comment]
Hmm, no; I think it should be up to the user to move it out. I personally would like to have a series lingering around for sometime because I watch anime like once or twice a month.

I went through the TODO list you showed me. I think Notifications page should be the highest priority. Yesterday also, I was having a good conversation in the MAL forums through the app, but it was hard to keep tab of the notifications.  When we are dealing with two three comment threads in the forum at the same, notifications tab would be a boon.

**Comment by sinofanger** [comment]
Also, did you read about the Prject NEON for Windows 10, a whole UI redesign like Android's material design. The early preview images looks good - a blend between iOS and Android, with the Aero effects of Windows 7.

**Comment by Drutol** [comment]
@sinofanger - offtop king xd

@Accelyte I don't agree with you here, if user wants to for example rate the show it'll just disappear and he'll have to search for it, or mistakenly chooses wrong status. It'd be more annoying that having this show present till next list refresh.

@sinofanger I'm thinking about skipping Android for one more weekend because of this notifications page.
I read about neon... it's not complete redesign as those articles claim. It supposedly adds more blur and animations and I'm not hyped for this look right now.

**Comment by sinofanger** [comment]
@Drutol  Yes, mu suggestion is also same. Focus on notifications page, it is a big necessity. 

Also, about Neon, the outlook app and taskbar seems a lot modified under Neon. Not sure, anyway Windows 10 is far from complete. I do not get the consistency feeling of a Mac in it. But honestly, I do not like Mac mainly because they do not have touch option and it will be hard make the transition, considering that I been using Window for 7 years now.  A couple of months back, I did try Mac OS, but it was not that good and productivity dropped due to the learning curve.

**Comment by Drutol** [comment]
Stop stop stop, it's not your issue to offtop here to xd
Go offtop somewhere else (chat,another issue) w/e.

**Comment by sinofanger** [comment]
Fine fine, I edited it :P

**Comment by Accelyte** [comment]
Just to make sure we're on the same page here I made a quick gif:

**Comment by Accelyte** [comment]
Whoops, accidentally clicked the wrong button.
To make sure we're on the same page I made a quick video: https://www.dropbox.com/s/hcr5gtl7z994pg2/mal.mp4
As you can see the series still stays until I click the refresh button.

If you want the user to continue editing the series (rate, edit details, etc.) the side tab is still open, so they can do that. The auto refresh that I'm talking about is just to show that the program is responding to the user input (at first I thought something was broken because I already completed the series and it was still showing).

**Comment by Accelyte** [comment]
P.S. offtopic: make the secondary tab text (General, Details, Reviews, etc.) slightly smaller so you can fit more buttons, it's a bit annoying that you have to click twice to find related series. (I mean, we can read the smaller font text so why not? And besides, it's just one more button...why not fit it all in?)

**Comment by Drutol** [comment]
Yeah we are talking about the same thing, and I still hold my opinion but I probably could make it more opaque or highlight the change in some way. I've thanked myself quite a few times for not making this disappear (when editing directly from list and not from details page).

As for details tabs... Right now it'll choose from 2 sizes where 1 is exactly wide enough to accommodate all tabs and one smaller not to hide whole "main" content. It depends on window size when launching. Changing font size is good idea too! I don't know why I didn't came up with it earlier. ^^

**Comment by Accelyte** [comment]
Well in that case you have to make sure to show it's been edited and it's not here to stay (though I have yet to understand your experience, mainly because that's what I would expect it to do ._.). I can see the W turn into a C but that's not obvious enough,

**Comment by Drutol** [comment]
I understand where your confusion is coming from. I'm not sure whether this change will make it into next update but it's already on my TODO list :)

**Comment by Accelyte** [comment]
Alright then thanks!
Great to see the app being actively developed :)

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/21939189/e8c009fe-d9be-11e6-9c42-adda4604ff9e.png)

Doned

**Comment by Accelyte** [comment]
that looks good :)
